In [1]:
import numpy as np

1.Tạo mảng mô phỏng dữ liệu

In [4]:
np.random.seed(50)
du_lieu_nhiet_do = np.round(np.random.uniform(10,30,size=(30)),2)
du_lieu_nhiet_do

array([19.89, 14.56, 15.11, 17.93, 17.55, 29.93, 18.16, 25.44, 25.21,
       16.2 , 16.93, 17.04, 12.91, 29.45, 28.18, 21.2 , 16.27, 27.76,
       23.49, 17.82, 20.14, 20.48, 28.56, 21.43, 23.37, 11.05, 16.54,
       11.13, 13.6 , 28.52])

In [6]:
nhiet_do_trung_binh = np.mean(du_lieu_nhiet_do)
print(f"Nhiêt độ trung bình:{nhiet_do_trung_binh}")

Nhiêt độ trung bình:20.194999999999997


2.Phân tích xu hướng nhiệt độ

In [9]:
ngay_max_nhiet_do = np.argmax(du_lieu_nhiet_do)+1
print("Ngày nhiệt độ cao nhất",ngay_max_nhiet_do)

6

In [10]:
ngay_min_nhiet_do = np.argmin(du_lieu_nhiet_do)+1
print("Ngày nhiệt độ thấp nhất",ngay_min_nhiet_do)

26

In [11]:
ngay_truoc = du_lieu_nhiet_do[:-1]
ngay_truoc

array([19.89, 14.56, 15.11, 17.93, 17.55, 29.93, 18.16, 25.44, 25.21,
       16.2 , 16.93, 17.04, 12.91, 29.45, 28.18, 21.2 , 16.27, 27.76,
       23.49, 17.82, 20.14, 20.48, 28.56, 21.43, 23.37, 11.05, 16.54,
       11.13, 13.6 ])

In [12]:
ngay_sau = du_lieu_nhiet_do[1:]
ngay_sau

array([14.56, 15.11, 17.93, 17.55, 29.93, 18.16, 25.44, 25.21, 16.2 ,
       16.93, 17.04, 12.91, 29.45, 28.18, 21.2 , 16.27, 27.76, 23.49,
       17.82, 20.14, 20.48, 28.56, 21.43, 23.37, 11.05, 16.54, 11.13,
       13.6 , 28.52])

In [13]:
chenh_lech = ngay_sau-ngay_truoc
print("Chênh lệch nhiệt độ:",chenh_lech)


Chênh lệch nhiệt độ: [ -5.33   0.55   2.82  -0.38  12.38 -11.77   7.28  -0.23  -9.01   0.73
   0.11  -4.13  16.54  -1.27  -6.98  -4.93  11.49  -4.27  -5.67   2.32
   0.34   8.08  -7.13   1.94 -12.32   5.49  -5.41   2.47  14.92]


In [17]:
print("Ngày có sự biến đổi nhiệt cao nhất")
ngay_chenh_lech_cao_nhat = np.argmax(np.diff(chenh_lech)) + 1
ngay_chenh_lech_cao_nhat

Ngày có sự biến đổi nhiệt cao nhất


12

3. Áp dụng Fancy Indexing

In [18]:
ngay_nhiet_do_cao_hon_20 = np.where(du_lieu_nhiet_do > 20)[0] + 1
print(f"Tất cả các ngày có nhiệt độ cao hơn 20 độ C: {ngay_nhiet_do_cao_hon_20}")

Tất cả các ngày có nhiệt độ cao hơn 20 độ C: [ 6  8  9 14 15 16 18 19 21 22 23 24 25 30]
