1. Đọc file txt

In [3]:
import numpy as np
path_1 = r'C:/Users/Admin/Documents/lesson1 Data science/Nguyen_Manh_Cuong_23174600007_DHKL17A1HN/DHKL17A1HN/Lab02/data/efficiency.txt'
path_2 = r'C:/Users/Admin/Documents/lesson1 Data science/Nguyen_Manh_Cuong_23174600007_DHKL17A1HN/DHKL17A1HN/Lab02/data/shifts.txt'
with open(path_1,'r',encoding='utf-8') as file:
    reads = file.readlines()
    data_1 = []
    for read in reads:
        read = read.strip()
        items = read.split(',')
        for item in items:
            try:
                data_1.append(float(item))
            except ValueError as e:
                print(f"Không thể chuyển đổi sang float")
data_1   

[94.0,
 97.0,
 114.0,
 117.0,
 117.0,
 59.0,
 133.0,
 71.0,
 86.0,
 137.0,
 120.0,
 138.0,
 138.0,
 62.0,
 108.0,
 115.0,
 89.0,
 137.0,
 96.0,
 138.0,
 131.0,
 87.0,
 75.0,
 127.0,
 122.0,
 59.0,
 70.0,
 130.0,
 119.0,
 129.0,
 97.0,
 114.0,
 132.0,
 149.0,
 138.0,
 99.0,
 79.0,
 69.0,
 69.0,
 64.0,
 89.0,
 82.0,
 115.0,
 59.0,
 107.0,
 82.0,
 81.0,
 124.0,
 73.0,
 85.0,
 125.0,
 105.0,
 78.0,
 84.0,
 50.0,
 50.0,
 86.0,
 103.0,
 55.0,
 88.0,
 67.0,
 129.0,
 54.0,
 92.0,
 108.0,
 81.0,
 51.0,
 115.0,
 91.0,
 107.0,
 85.0,
 61.0,
 96.0,
 132.0,
 141.0,
 50.0,
 64.0,
 149.0,
 103.0,
 62.0,
 92.0,
 134.0,
 125.0,
 118.0,
 56.0,
 118.0,
 97.0,
 53.0,
 126.0,
 102.0,
 128.0,
 65.0,
 70.0,
 149.0,
 108.0,
 73.0,
 129.0,
 63.0,
 135.0,
 98.0]

In [6]:
with open(path_2,'r',encoding='utf-8') as file:
    reads = file.readlines()
    data_2 = []
    for read in reads:
        read = read.strip()
        items = read.split(',')
        for item in items:
            try:
                data_2.append(str(item))
            except ValueError as e:
                print("Không thể chuyển đổi sang str")
data_2

['Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Night',
 'Morning',
 'Afternoon',
 'Night',
 'Morning',
 'Night',
 'Morning',
 'Afternoon',
 'Night',
 'Night',
 'Afternoon',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Night',
 'Night',
 'Night',
 'Night',
 'Afternoon',
 'Night',
 'Night',
 'Night',
 'Night',
 'Night',
 'Morning',
 'Afternoon',
 'Night',
 'Night',
 'Afternoon',
 'Night',
 'Afternoon',
 'Morning',
 'Night',
 'Night',
 'Morning',
 'Night',
 'Morning',
 'Morning',
 'Night',
 'Morning',
 'Night',
 'Night',
 'Night',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Night',
 'Morning',
 'Afternoon',
 'Night',
 'Night',
 'Night',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Morning',
 'Night',
 'Night',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Night',
 'Morning',
 'Morning',
 'Afternoon',
 'Morning',
 'Night',
 'Afternoon',
 'Afternoon',
 'Afternoon',
 'Morning',
 'Morning',
 'Morning',
 'Afternoon',
 'Afternoon',
 'Night',


2. Tạo numpy array với np_efficiency và kiểm tra dữ liệu của nó

In [3]:
np_efficiency = np.array(data_1,dtype=int)
np_efficiency

array([ 94,  97, 114, 117, 117,  59, 133,  71,  86, 137, 120, 138, 138,
        62, 108, 115,  89, 137,  96, 138, 131,  87,  75, 127, 122,  59,
        70, 130, 119, 129,  97, 114, 132, 149, 138,  99,  79,  69,  69,
        64,  89,  82, 115,  59, 107,  82,  81, 124,  73,  85, 125, 105,
        78,  84,  50,  50,  86, 103,  55,  88,  67, 129,  54,  92, 108,
        81,  51, 115,  91, 107,  85,  61,  96, 132, 141,  50,  64, 149,
       103,  62,  92, 134, 125, 118,  56, 118,  97,  53, 126, 102, 128,
        65,  70, 149, 108,  73, 129,  63, 135,  98])

In [4]:
type(np_efficiency)

numpy.ndarray

3.Tạo numpy array với np_shifts và kiểm tra dữ liệu của nso

In [5]:
np_shifts = np.array(data_2,dtype=str)
np_shifts

array(['Afternoon', 'Afternoon', 'Afternoon', 'Morning', 'Afternoon',
       'Night', 'Morning', 'Afternoon', 'Night', 'Morning', 'Night',
       'Morning', 'Afternoon', 'Night', 'Night', 'Afternoon', 'Morning',
       'Afternoon', 'Afternoon', 'Morning', 'Night', 'Night', 'Night',
       'Night', 'Afternoon', 'Night', 'Night', 'Night', 'Night', 'Night',
       'Morning', 'Afternoon', 'Night', 'Night', 'Afternoon', 'Night',
       'Afternoon', 'Morning', 'Night', 'Night', 'Morning', 'Night',
       'Morning', 'Morning', 'Night', 'Morning', 'Night', 'Night',
       'Night', 'Morning', 'Morning', 'Morning', 'Afternoon', 'Night',
       'Morning', 'Afternoon', 'Night', 'Night', 'Night', 'Afternoon',
       'Morning', 'Morning', 'Morning', 'Morning', 'Night', 'Night',
       'Morning', 'Morning', 'Morning', 'Afternoon', 'Night', 'Morning',
       'Morning', 'Afternoon', 'Morning', 'Night', 'Afternoon',
       'Afternoon', 'Afternoon', 'Morning', 'Morning', 'Morning',
       'Afternoon', 'A

In [6]:
type(np_shifts)

numpy.ndarray

4.Tính hiệu suất sản xuất trung bình của nhân viên làm việc trong ca 'Morning'

In [7]:
morning_efficiency = np_efficiency[np_shifts=='Morning']
morning_efficiency

array([117, 133, 137, 138,  89, 138,  97,  69,  89, 115,  59,  82,  85,
       125, 105,  50,  67, 129,  54,  92,  51, 115,  91,  61,  96, 141,
        62,  92, 134,  97,  53, 149, 108,  73])

In [8]:
avg = np.mean(morning_efficiency)
avg

np.float64(96.8529411764706)

5.Tính hiệu suất trung bình của nhân viên làm việc khác ca morning

In [9]:
diff_morning_efficiency = np_efficiency[np_shifts!='Morning']
diff_morning_efficiency

array([ 94,  97, 114, 117,  59,  71,  86, 120, 138,  62, 108, 115, 137,
        96, 131,  87,  75, 127, 122,  59,  70, 130, 119, 129, 114, 132,
       149, 138,  99,  79,  69,  64,  82, 107,  81, 124,  73,  78,  84,
        50,  86, 103,  55,  88, 108,  81, 107,  85, 132,  50,  64, 149,
       103, 125, 118,  56, 118, 126, 102, 128,  65,  70, 129,  63, 135,
        98])

In [10]:
avg_1 = np.mean(diff_morning_efficiency)
avg_1

np.float64(98.93939393939394)

6.Tạo mảng dữ liệu có cấu trúc với gồm shiffts là kiểu văn bản U10 và efficiency là float

In [11]:
worker = np.array(list(zip(data_2,data_1)),dtype=[('data_2','U10'),('data_1','float')])
worker

array([('Afternoon',  94.), ('Afternoon',  97.), ('Afternoon', 114.),
       ('Morning', 117.), ('Afternoon', 117.), ('Night',  59.),
       ('Morning', 133.), ('Afternoon',  71.), ('Night',  86.),
       ('Morning', 137.), ('Night', 120.), ('Morning', 138.),
       ('Afternoon', 138.), ('Night',  62.), ('Night', 108.),
       ('Afternoon', 115.), ('Morning',  89.), ('Afternoon', 137.),
       ('Afternoon',  96.), ('Morning', 138.), ('Night', 131.),
       ('Night',  87.), ('Night',  75.), ('Night', 127.),
       ('Afternoon', 122.), ('Night',  59.), ('Night',  70.),
       ('Night', 130.), ('Night', 119.), ('Night', 129.),
       ('Morning',  97.), ('Afternoon', 114.), ('Night', 132.),
       ('Night', 149.), ('Afternoon', 138.), ('Night',  99.),
       ('Afternoon',  79.), ('Morning',  69.), ('Night',  69.),
       ('Night',  64.), ('Morning',  89.), ('Night',  82.),
       ('Morning', 115.), ('Morning',  59.), ('Night', 107.),
       ('Morning',  82.), ('Night',  81.), ('Night', 124

7.Sắp xếp workers theo efficiency

In [12]:
sorted_efficiency = np.sort(worker,order='data_1')
sorted_efficiency

array([('Afternoon',  50.), ('Morning',  50.), ('Night',  50.),
       ('Morning',  51.), ('Morning',  53.), ('Morning',  54.),
       ('Night',  55.), ('Night',  56.), ('Morning',  59.),
       ('Night',  59.), ('Night',  59.), ('Morning',  61.),
       ('Morning',  62.), ('Night',  62.), ('Night',  63.),
       ('Afternoon',  64.), ('Night',  64.), ('Afternoon',  65.),
       ('Morning',  67.), ('Morning',  69.), ('Night',  69.),
       ('Afternoon',  70.), ('Night',  70.), ('Afternoon',  71.),
       ('Morning',  73.), ('Night',  73.), ('Night',  75.),
       ('Afternoon',  78.), ('Afternoon',  79.), ('Night',  81.),
       ('Night',  81.), ('Morning',  82.), ('Night',  82.),
       ('Night',  84.), ('Morning',  85.), ('Night',  85.),
       ('Night',  86.), ('Night',  86.), ('Night',  87.),
       ('Afternoon',  88.), ('Morning',  89.), ('Morning',  89.),
       ('Morning',  91.), ('Morning',  92.), ('Morning',  92.),
       ('Afternoon',  94.), ('Afternoon',  96.), ('Morning',  96

In [13]:
highest=sorted_efficiency[-1]

In [14]:
lowest=sorted_efficiency[0]

In [15]:
print(f"ca làm việc có hiệu suất cao nhất:{highest['data_2']} {(highest['data_1'])}")

ca làm việc có hiệu suất cao nhất:Night 149.0


In [16]:
print(f"ca làm việc có hiệu suất thấp nhất:{lowest['data_2']} {(lowest['data_1'])}")

ca làm việc có hiệu suất thấp nhất:Afternoon 50.0
